 #Makefile
 #Created on: 20 avr. 2021
 #    Author: nour tnani and zakarya souid

     # Define project name here
PROJECT = Robotique

#Define path to the e-puck2_main-processor folder
GLOBAL_PATH = ../../lib/e-puck2_main-processor

#Source files to include
CSRC += ./main.c \
		./walls.c\

#Header folders to include
INCDIR += 

#Jump to the main Makefile
include $(GLOBAL_PATH)/Makefile